# fly.toml
app = "codechat"
primary_region = "fra"

[build]
  # Uses the repo's Dockerfile (no changes needed)

[env]
# ensure the server binds correctly (many Node apps honor these)
PORT = "8084"
HOST = "0.0.0.0"

[[mounts]]
  source = "instances"
  destination = "/codechat/instances"

[http_service]
  internal_port = 8084
  force_https = true
  auto_stop_machines = false         # Keep machine alive to avoid WS drop/QR churn
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 40


  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "120s"
    method = "GET"
    path = "/docs"        
    # If the repo has a dedicated health route (e.g., /health), switch to that.

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512